### ISSUE TITLE
Please update for compatibility with Django 1.7+

### ISSUE THREAD

**Issue by onlyjob** [osuosl-cookbooks/ganeti_webmgr#17]
Debian "Jessie" was released with Django 1.7.7. Please update Ganeti Web Manager for compatibility with Django 1.7+.

**Comment by tschuy** [comment]
This issue was moved to osuosl/ganeti_webmgr#59

**Comment by tschuy** [comment]
This is repo is for the cookbook, so I've moved it to the repo for the project itself.

**Comment by onlyjob** [comment]
Sorry, I've accidentally entered issue into wrong tab in my browser...
